### ISSUE TITLE
Cannot run Tune/Conform on Linux

### ISSUE THREAD

**Issue by Alkaid-Benetnash** [reeselevine/webgpu-litmus#42]
Hi,
Seeing the following error on Linux with Chrome version 110.0.5481.77 (64-bit).

![image](https://user-images.githubusercontent.com/9082286/218171387-d5791705-7ae1-41f2-8f83-a23fd1674a80.png)

Running from a laptop with both intel and nvidia GPU. Tried both.

**Comment by reeselevine** [comment]
Hi, sorry for the late response but I just saw this.

Yeah, WebGPU on Linux is still tricky to get working. To get it working, we've used the following steps:
1.) You need to use Chrome Dev: https://www.google.com/chrome/dev/
2.) In `chrome://flags', search for "webgpu" and enable the flags you see there.
4.) When launching Chrome, you need to pass the flag `--enable-features=Vulkan`.

Hopefully WebGPU on Linux starts getting more support so that it becomes more push button soon.

**Comment by Alkaid-Benetnash** [comment]
Hi,
I missed the flag `--enable-features=Vulkan`.
And besides, for future reference, I also needs `--use-gl=egl` as I am using a linux desktop environment.
Anyway, all tests runs succesfully on the latest chromium release with the above command-line options.
